import React from "react";
import Head from "next/head";

function About() {
  return (
    <>
      <Head>
        <title>Sample UI | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-2xl font-bold">About</h1>
        <p className="pt-5">
          Ut commodo ea velit et commodo nostrud aute consequat exercitation.
          Aute non dolor ut ipsum. Enim ut sint incididunt dolor laboris. Labore
          qui deserunt exercitation do. Labore voluptate velit irure enim
          voluptate occaecat occaecat nulla. Ea veniam ex est sunt. Lorem aliqua
          fugiat enim irure veniam culpa aliqua dolor dolore occaecat consequat
          veniam elit est. Incididunt est eiusmod occaecat sint do anim. Ullamco
          mollit occaecat culpa qui non in reprehenderit nisi minim amet commodo
          officia. Dolor velit occaecat Lorem labore occaecat minim excepteur.
          Fugiat adipisicing deserunt consequat excepteur do sit ipsum eu nulla
          incididunt exercitation. Aliquip occaecat fugiat elit anim fugiat nisi
          do excepteur cillum eiusmod eiusmod cillum. Qui laborum consectetur
          fugiat incididunt cillum minim eiusmod veniam ut esse magna magna
          minim. Qui dolore deserunt Lorem nostrud magna eiusmod adipisicing
          laboris nulla sint et consectetur voluptate. Lorem velit consequat
          aute eu. Eu nisi ullamco dolor proident culpa cupidatat ullamco enim.
          Commodo deserunt proident anim do minim Lorem. Tempor proident aliqua
          velit Lorem est ullamco. Occaecat reprehenderit mollit nostrud
          occaecat labore. Anim adipisicing cupidatat esse nulla ut eu officia
          cillum dolor aliquip. Velit minim nisi enim adipisicing voluptate
          occaecat. Nulla do elit pariatur aliquip aliqua qui. Anim laborum ad
          officia amet. Laboris amet exercitation incididunt consectetur tempor
          eu. Irure aliqua sit aliqua ipsum cupidatat et. In ex exercitation ut
          fugiat ullamco ullamco. Mollit reprehenderit consectetur magna quis
          minim dolore adipisicing proident ad duis occaecat. Aliquip incididunt
          sint pariatur cillum dolore fugiat nulla ex ad aute proident. Eiusmod
          ad velit dolor reprehenderit. Officia ipsum sunt sunt pariatur
          exercitation esse sit incididunt qui occaecat cupidatat velit. Veniam
          do fugiat culpa nostrud ut. Dolor aute enim non officia exercitation
          pariatur esse ex veniam. Excepteur pariatur esse et eu proident labore
          consequat duis nulla id pariatur officia. Est tempor ipsum cupidatat
          officia. Culpa irure cillum cillum eu tempor incididunt irure velit.
          Commodo pariatur amet consectetur irure tempor mollit esse anim
          aliquip sit. Officia velit incididunt est nisi. Velit aute voluptate
          ad Lorem mollit dolore. Cillum consectetur ad deserunt Lorem do magna
          cillum incididunt.
        </p>
      </div>
    </>
  );
}

export default About;
