import React from "react";
import Head from "next/head";
import Link from "next/Link";

export const getStaticProps = async () => {
  const result = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await result.json();

  return {
    props: { users: data },
  };
};

function Postings({ users }) {
  return (
    <>
      <Head>
        <title>Sample UI | Postings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="font-bold text-2xl pb-4">Postings</h1>
        {users.map((user) => (
          <Link href={`/postings/${user.id}`} key={user.id}>
            <div className="bg-slate-300 p-4 mb-2 border-l-4 hover:border-l-slate-500 cursor-pointer">
              <a>{user.name}</a>
            </div>
          </Link>
        ))}
      </div>
    </>
  );
}

export default Postings;
